version: '3'
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20200826
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=20
      - GRID_BROWSER_TIMEOUT=300
  chrome:
    image: selenium/standalone-chrome:86.0
    shm_size: "2g"
    depends_on:
      - selenium-hub
    environment:
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
    ports:
      - "5900"
    links:
      - selenium-hub
